name: cd

on: [push, pull_request]

env:
  SOLC_VERSION: ${{ secrets.SOLC_VERSION }}

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.x]
        python: [3.8.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python tools
        run: |
          sudo apt-get -y install libssl-dev python3-dev python3-pip
          pip3 install solc-select
          pip3 install slither-analyzer
          pip3 install mythril

      - name: Setup Solc
        run: |
          solc-select install ${{ env.SOLC_VERSION }}
          solc-select use ${{ env.SOLC_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies with dev deps
        run: yarn install --production=false

      - name: Hardhat compile
        run: yarn run compile --force

      - name: Test with coverage
        run: yarn run coverage

      - name: Linters & Formatters
        run: yarn run hook:pre-push

      - name: Analyze
        run: slither contracts/ && myth analyze --solc-json mythril.config.json contracts/*.sol
